# Generated by Django 2.0.5 on 2018-05-30 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-create_date']},
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='create_day',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='last_day',
            new_name='last_date',
        ),
    ]
