# Generated by Django 2.0.5 on 2018-05-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20180530_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='last_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
