# Generated by Django 2.0.5 on 2018-05-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20180530_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='last_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
