# Generated by Django 2.0.6 on 2018-06-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('kind', models.CharField(max_length=20)),
                ('link', models.URLField()),
                ('img_link', models.URLField()),
            ],
        ),
    ]
